const EVENTS = {

  JOIN_ROOM: "JOIN_ROOM",
  LEAVE_ROOM: "LEAVE_ROOM",

  USER_JOINED: "USER_JOINED",
  ROOM_USERS: "ROOM_USERS",

  CODE_CHANGE: "CODE_CHANGE",
  RECEIVE_CODE: "RECEIVE_CODE",
  SYNC_CODE: "SYNC_CODE",

  SEND_MESSAGE: "SEND_MESSAGE",
  RECEIVE_MESSAGE: "RECEIVE_MESSAGE",
};

module.exports = EVENTS;